---
- name: Manage EC2 instances
  hosts: aws_ec2
  become: yes
  gather_facts: yes
  
  pre_tasks:
    - name: Set OS-specific variables
      set_fact:
        ansible_ssh_user: "{{ 'ubuntu' if tags.OS == 'ubuntu' else 'ec2-user' }}"
      
  roles:
    - system_updates
    - docker

  tasks:
    - name: Report disk usage
      command: df -h
      register: disk_usage
      
    - name: Show disk usage
      debug:
        var: disk_usage.stdout_lines